version: '3.8'

services:
#  postgres:
#    image: postgres:15
#    environment:
#      POSTGRES_USER: ai_fitness
#      POSTGRES_PASSWORD: ai_fitness_pass
#      POSTGRES_DB: ai_fitness_db
#    volumes:
#      - pgdata:/var/lib/postgresql/data
#    ports:
#      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    env_file:
      - ./backend/.env
    depends_on:
 #     - postgres
      - redis
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    dns:
      - 1.1.1.1
      - 8.8.8.8
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build: ./frontend
    container_name: ai-fitness-frontend
    ports:
      - "8080:8080"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
    restart: always

  worker:
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    depends_on:
#      - postgres
      - redis
    volumes:
      - ./backend:/app
    command: celery -A app.worker.celery_app worker --loglevel=info

volumes:
  pgdata:
